create table Patients_1(
Patient_id number(3),
Patient_name varchar(30),
Patient_email varchar(30),
Patient_Registered_date date)

create table Medicines_1(
Medicine_id number(3),
Medicine_name varchar(30)
)

create table Prescriptions_1(
Prescription_id number(3),
Prescribed_date date,
Patient_id number(3),
Medicine_name varchar(30)
)

--drop table Prescriptions_1 purge

create table Reception(
id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
Prescription_id number(3),
Medicine_id number(3)
)

alter table Patients_1
add constraint pk_patientId_1 primary key(Patient_id)

alter table Patients_1
modify(patient_name NOT NULL)

alter table Patients_1
modify(patient_email UNIQUE)

alter table Medicines_1
add constraint pk_medicineId_1 primary key(medicine_id)

alter table Medicines_1
modify (medicine_name NOT NULL)

alter table Prescriptions_1
add constraint pk_presId primary key(prescription_id)

alter table Prescriptions_1
add constraint fk_patientId_0 foreign key (patient_id) references Patients(patient_id)

alter table Prescriptions_1
modify (medicine_name NOT NULL)


alter table Reception
add constraint fk_prescId foreign key(prescription_id) references Prescriptions(prescription_id)

alter table Reception
add constraint fk_medId foreign key(medicine_id) references Medicines(medicine_id)

